name: Package and Upload Velopack Installer

on:
  push:
    branches:
      - main

jobs:
  package-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout built files repo
        uses: actions/checkout@v4

      - name: Read version from file
        id: get-version
        shell: pwsh
        run: |
          $version = Get-Content version.txt | Out-String -NoNewline
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Install Velopack CLI
        run: dotnet tool install -g vpk

      - name: Package with Velopack
        run: vpk pack --packId padkey --packVersion "${{ steps.get-version.outputs.version }}" --packDir publish --mainExe PadKey.exe --outputDir output

      - name: List files after pack
        run: ls -R

      - name: Prepare upload folder
        run: |
          mkdir upload
          Copy-Item -Path output/* -Destination upload/ -Recurse

      - name: Push Velopack files to release repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          cd upload
          git init
          git add .
          git commit -m "Velopack installer v${{ steps.get-version.outputs.version }}"
          git branch -M main
          git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/Silen1t/PadKey-Releases.git
          git push -f origin main
