name: Package and Upload Velopack Installer

on:
  push:
    branches:
      - main

jobs:
  package-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from file
        id: get-version
        shell: pwsh
        run: |
          $version = Get-Content version.txt | Out-String -NoNewline
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Install Velopack CLI
        run: dotnet tool install -g vpk

      - name: Package with Velopack
        run: vpk pack --packId PadKey --packVersion "${{ steps.get-version.outputs.version }}" --packDir publish --mainExe PadKey.exe --outputDir output

      - name: List files after pack
        run: ls -R output

      # Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          release_name: v${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          auth-token: ${{ secrets.GH_TOKEN }}

      # Upload all Velopack files to the release
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/PadKey-${{ steps.get-version.outputs.version }}-full.nupkg
          asset_name: PadKey-${{ steps.get-version.outputs.version }}-full.nupkg
          asset_content_type: application/octet-stream

      - name: Upload portable zip
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/PadKey-win-Portable.zip
          asset_name: PadKey-win-Portable.zip
          asset_content_type: application/zip

      - name: Upload setup exe
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/PadKey-win-Setup.exe
          asset_name: PadKey-win-Setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
