name: Package and Upload Velopack Installer

on:
  push:
    branches:
      - main

jobs:
  package-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout built files repo
        uses: actions/checkout@v4

      - name: Read version from file
        id: get-version
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Install Velopack CLI
        run: dotnet tool install -g vpk

      - name: Package with Velopack
        run: vpk pack --packId padkey --packVersion ${{ steps.get-version.outputs.version }} --packDir .\publish --mainExe PadKey.exe

      - name: Prepare upload folder
        run: |
          mkdir upload
          cp -r .vpk/* upload/

      - name: Push Velopack files to release repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          cd upload
          git init
          git add .
          git commit -m "Velopack installer v${{ steps.get-version.outputs.version }}"
          git branch -M main
          git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/<YOUR_USER>/<YOUR_RELEASES_REPO>.git
          git push -f origin main
