name: Package and Upload Velopack Installer

on:
  push:
    branches:
      - main

jobs:
  package-upload:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read version from file
        id: get-version
        shell: pwsh
        run: |
          $version = Get-Content version.txt | Out-String -NoNewline
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Install Velopack CLI
        run: dotnet tool install -g vpk

      - name: Package with Velopack
        run: vpk pack --packId PadKey --packVersion "${{ steps.get-version.outputs.version }}" --packDir publish --mainExe PadKey.exe --outputDir output --packTitle "PadKey" --packAuthors "Yousef Alsaleh, aka Silent" --shortcuts "Desktop,StartMenu” --runtime "win-x64" --delta None

      - name: List files after pack
        run: ls -R output

      # Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          release_name: v${{ steps.get-version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            ./output/PadKey-${{ steps.get-version.outputs.version }}-full.nupkg
            ./output/PadKey-win-Portable.zip
            ./output/PadKey-win-Setup.exe
            ./output/RELEASES
            ./output/assets.win.json
            ./output/releases.win.json
          token: ${{ secrets.GH_TOKEN }}
          opts.auth: ${{ secrets.GH_TOKEN }}